### ISSUE TITLE
Folders with .cdi games are not listed

### ISSUE THREAD

**Issue by PapiFed** [Louhike/Ugly-GDEmu-Games-Manager#1]
During scanning of SD card the folders that contain games in .cdi format are not listed.
Problem encountered using v. 0.5.1

![image](https://user-images.githubusercontent.com/62958761/85219044-ac97f300-b3a0-11ea-8768-97d324f5a1eb.png)

![image](https://user-images.githubusercontent.com/62958761/85219059-cafdee80-b3a0-11ea-9756-3e48b5d7be2c.png)

**Comment by Louhike** [comment]
For now, only GDI games are managed in this tool. Currently, GDEmu can use:
-  GDI (for GD-ROMs)
-  CDI
-  CCD+IMG+SUB
-  MDS+MDF
-  ISO (as data carriers for homebrew)
So I'll try to manage all them next.

**Comment by Louhike** [comment]
CDI is managed with version 0.6.5.
