### ISSUE TITLE
Games on multiple discs linked to a single folder

### ISSUE THREAD

**Issue by PapiFed** [Louhike/Ugly-GDEmu-Games-Manager#2]
Games that use multiple discs have an identical "SD Folder" reference instead of having their own folder reference.

![image](https://user-images.githubusercontent.com/62958761/85219101-23cd8700-b3a1-11ea-91f4-3417545497a4.png)

![image](https://user-images.githubusercontent.com/62958761/85219116-3d6ece80-b3a1-11ea-9be5-0defc578b527.png)

**Comment by Louhike** [comment]
Fixed by commit https://github.com/Louhike/Ugly-GDEmu-Games-Manager/commit/992f7dccbab12af5c7fc270eaf1b2545057e3e45
