### ISSUE TITLE
UGGM_0_6_1 STOPPED WORKING

### ISSUE THREAD

**Issue by bman83** [Louhike/Ugly-GDEmu-Games-Manager#34]
**Describe the bug**
The program was working having processed and shrunk 32 ntsc games. And now will not load.

**To Reproduce**
1. Go to '*.exe'
2. Click on 'scan'
3. See error

**Expected behavior**
I expected games folder to load

**Screenshots**
https://img.raymond.cc/blog/wp-content/uploads/2009/08/stopped_working_no_WER.png

**Desktop (please complete the following information):**
 - OS: windows 7
 
**Additional context**

**Comment by Louhike** [comment]
When you say it will not load, you mean it won't start anymore? Or it start but copy/shrink isn't working anymore?

**Comment by bman83** [comment]
Hi Lou,

Thanks for your email.

I found out the game "conflict zone" does not work when being shrunk. So
the issue Occurred after your software processed "conflict zone" and then
froze during the shrink process.

I restarted  UGLY  and then I could not process anymore files

Once again.

Thankyou for your work it's much appreciated.

Are you working on any other programs?

A SONY PS2 version of your UGLY software will be great

**Comment by Louhike** [comment]
Thanks for the information, I'll make some tests with Conflict Zone to understand what went wrong and I'll keep you updated quickly.
If you know in which folder it was copied, you could try to remove it for now.

> Are you working on any other programs?
I am not for now, but I might in the future. I would like to focus on the Dreamcast for the time being. I might try the PS2 as I have one, but I don't know when :/.

**Comment by bman83** [comment]
Hi Lou,

Thanks for the email.

I have been loading the games onto a gdemu, I downloaded the TOSEC rom set.
I have been processing the USA NTSC files as they work best with VGA.

The following games also have issues when shrinking
1 CONFLICT ZONE
2 CHICKEN RUN (PAL)
3 DUCATTI WORLD
4  MATT HOFFMAN BMX
5 NIGHTMARE CREATURES
6 OMIKRON
7 BOTH SOUTHPARK GAMES.

When scrolling in the gdmenu 0.6 and you highlight the above games the
screen goes black. I think that means the iso header is damaged when trying
to load the disc image picture

If you could verify that the images are shrunk somehow that would be good.

Also if there was a function to show if the isos are compatible with VGA
that would be good. There is a list here.

List of games that DON'T WORK with VGA Period:

21 - Two One
Airforce Delta
Black Matrix (game boots, sound is heard, no image is displayed)
Caesar's Palace 2000
Cho Hatsumei Boy Kanipan: Bousou Robot no Nazo
D Vine Luv
Dance Dance Revolution 2nd Mix
Dance Dance Revolution Club Version
Dancing Blade Katteni Momo Tenshi II: Tears of Eden
deSPIRIA
Dino Crisis (menu can be force booted, but actual game crashes)
E.S
ECW Anarchy Rulz
ECW Hardcore Revolution
Eisei Meijin III: Game Creator Yoshimura Nobuhiro no Zunou
Imperial no Taka: Fighter of Zero
Jikkyo Powerful Pro Yakyu: Dreamcast Edition
Jinsei Game For Dreamcast
Jissen Pachislo Hissyouhou @ VPachi
July
King of Fighters '99 Dream Match
King of Fighters '99 Evolution
Kita He - Photo Memories
Konohana 2: Todoka Nai Requiem
Konohana: True Report
L.O.L - Lack of Love
Langrisser Millennium
Last Blade 2
Mahjong Taikai II Special
MTV Skateboarding
Nanatsu no Hikan Senritsu no Hohoemi
Nijyuei
Nobunaga no Yabou: Reppuuden
Nobunaga no Yabou: Shouseiroku
Plasma Sword
Psychic Force 2012
Psychological Game
Rayblade
Ring Terror's Realm
Rune Caster
Sangokushi VI With Power Kit
Soul Fighter
Sunrise Eiyuutan
Tanaka Torahiko no Urutoraryu Syogi Ibisyaanaguma Hen
Winning Post 4 Program 2000
World Neverland 2 Plus: The Waktic Republic of Pluto
WWF Attitude
Yukyu Gensokyoku 3: Perpetual Blue
Yumebaken '99 Internet

**Comment by bman83** [comment]
Hi Lou,

Here is the VGA compatibility list
https://www.epforums.org/showthread.php?56169-Dreamcast-VGA-Compatability-list-amp-Guide
thanks to zorlon

**Comment by Louhike** [comment]
I've added a timeout to avoid this problem with non working games with an error recommending the user to copy the game without shrinking. I've contacted the developer of gditools and he is unsure of why this happens for now.

I might make a blacklist to warn the user against shrinking the list of games which are known as not working.

**Comment by Louhike** [comment]
It won't fix the problem but at leat the program won't crash anymore.

**Comment by Louhike** [comment]
And it will be released with 0.6.2 version.

**Comment by bman83** [comment]
Hi Lou I tested the games they work when not shrunk

**Comment by bman83** [comment]
Hi Lou,

Hi have tested the NTSC TOSEC SET THESE GAMES CANNOT BE SHRUNK.

[image: Capture.PNG]

**Comment by Louhike** [comment]
I unfortunatly can't see your capture. They do no work when you try to launch them on GDEmu? Or is it the tool which failed?
I just tried with some of them and had no problem.

Thanks for the feedback!
