### ISSUE TITLE
Allow window to display well on smaller screens

### ISSUE THREAD

**Issue by gingerbeardman** [Louhike/Ugly-GDEmu-Games-Manager#44]
**Is your feature request related to a problem? Please describe.**
- Cannot use the window on small screens

**Describe the solution you'd like**
- window layout should cope with small screens

**Describe alternatives you've considered**
- change to higher resolution

**Additional context**
- my screen has native resolution of 640x480 (same one I use for my Dreamcast)
- whilst i can change to high resolutions they are less reasable as they are not the native screen size

**Comment by Louhike** [comment]
I'm actually working on a feature to fold/unfold the different parts of the software (I can provide a screenshot it's unclear), do you think it would help?
I try to make to improve readability for smaller resolutions but I have some difficulties to do so while also adding new features. If you (or someone else) has any idea how to do so, I'll be pleased to read them. But in any case, it's definitly something I'm working on.

**Comment by gingerbeardman** [comment]
That sounds promising.

Readability is not the problem, but rather that the window has a minimum/expected width of around 1000px meaning the right half of the window gets cut off on buy 640x480 display. Even at 800x600 parts are not accessible. At 1024x768 I can see everything.

Existing:
![shs31p8zix651](https://user-images.githubusercontent.com/49612/101241908-2d9a3b00-36f2-11eb-9f40-e755a86444cd.png)

Possible?
- window elements expand to fit at red lines
- option to hide folder column might help, but I see the columns adjusting dynamically
- sidebar green line could be folded
- apply button and menu checkbox would need to be reloacted

<img width="300" alt="Screen shot 2020-12-05 at 12 11 03" src="https://user-images.githubusercontent.com/49612/101242766-6f77b100-36f3-11eb-998d-864301d63ce4.png">

I understand this is a bit of effort

As it is I use your app to do the initial load and then switch the MadSheep app to do any work after that.

**Comment by Louhike** [comment]
Thanks for the recommandations!
I tried to make a new version this morning (unreleased for now, I'll release it with other changes with the 0.6.3 version). I used adjustements I was already working on and some of your recommandations. I will keep this issue opened to implement some of your other recommandations in another version.
I attached binaries of the software with thoses changes if you want to try them. If you have any feedback on it, please provide it here.
[UGGM_with_changes_for_size.zip](https://github.com/Louhike/Ugly-GDEmu-Games-Manager/files/5647109/UGGM_with_changes_for_size.zip)

**Comment by gingerbeardman** [comment]
Here is what I see, will have a think on it.

![2020-12-05 15_49_47-Greenshot](https://user-images.githubusercontent.com/49612/101247441-9d6bee00-3711-11eb-8f8b-b22d36731c4a.png)

**Comment by Louhike** [comment]
I don't know if it's obvious but you can resize the different parts with the gray bars.

**Comment by gingerbeardman** [comment]
I did eventually figure that out! Thanks

I'll try using your test version and see how it feels.

Comparing to MadSheep SD Maker (random image from google) 770px wide

![osayt9nuh3m41](https://user-images.githubusercontent.com/49612/101262938-e6379d00-3739-11eb-90d0-a873b249715c.jpg)

**Comment by gingerbeardman** [comment]
This beta version is not really doing it for me. Sorry

**Comment by Louhike** [comment]
No problem. Is the right part the biggest problem ? Maybe I should let the ability to fold it at least, until I find a way to display items in a more efficient way. Do you think it would help ?

**Comment by gingerbeardman** [comment]
I think the main problem is that only half the window is list. The rest is chrome that I never really use.

IMHO an app that is for managing the games should focus on the games (list)

**Comment by Louhike** [comment]
I just released 0.6.3 version which is a modified version of the beta I provided. But i'm gonna make other changes on 0.6.4 version. I'll try to remove the right part. I guess I'll put an help icon for the upper part (and display it on a popup). I'm not sure what I will do for the log though (with info and errors messages). I need to think about it.
Thanks for your messages and proposals, it is really helpful.

**Comment by gingerbeardman** [comment]
My pleasure?

My thoughts compared to MadSheep app - what is the log needed? The most recent message is all I ever read. This could be in status item.

I will do a wireframe mockup later on of how I see the window looking.

**Comment by gingerbeardman** [comment]
This is how I envisage it looking:

This is just a guide to hierarchy and use of space, not exact placement!

<img width="681" alt="Screen shot 2020-12-11 at 15 23 30" src="https://user-images.githubusercontent.com/49612/101921371-d6e6a280-3bc4-11eb-957f-c75d73967cba.png">

**Comment by Louhike** [comment]
Wow, great mockup! I think I will use it for the 0.6.3 version.

**Shrink** => A compatibility list is a feature I want to add, but it will require a lot of testing. I would also like to have a better integration with GDITools. I was in contact with the developer some months ago (a great guy), but we both had other things to do at the time. I'll try to see what can be done.

I was doing the shrinking on local before but it was actually longer on my PC, but I guess it depends on your hardware (SSD or HDD, SD card adapter speed, etc.). The slowness annoys, I want to work on it.

**No Local Folder** => This is also something I want to add. I'm planning to add it for the 0.7 version. I think I'll do a 0.6.4 version and then work on this one.

**Comment by Louhike** [comment]
640*480 seems now ok with version 0.7.0. Will be released in coming days with 0.7.0 version (currently in testing).
![image](https://user-images.githubusercontent.com/450826/102791248-022c7700-43a7-11eb-9a6b-cab49706e433.png)

**Comment by gingerbeardman** [comment]
Amazing work!
