### ISSUE TITLE
Does not cope with folders including .cdi images

### ISSUE THREAD

**Issue by gingerbeardman** [Louhike/Ugly-GDEmu-Games-Manager#47]
**Describe the bug**
Does not cope with folders including .cdi images

**To Reproduce**
1. use MadSheep to add some games with .cdi images
2. manage the same SD card with UGGM

**Expected behavior**
- neither app should undo the changes of the other

**Desktop (please complete the following information):**
 - OS: Win 10 (64-bit)

**Comment by Louhike** [comment]
Yes, the software does not work with CDI files for now. Until now, maybe I should just the folders alone, without trying to do anything with the files. But I wouldn't be able to create the menu index in this case until the software can manage CDI files.

**Comment by gingerbeardman** [comment]
Thanks, this is a bit of deal breaker because I have a bunch of CDI home-brew. I have to do a second pass with MadSheep to re-add them after using UGGM.

Your suggestion sounds like a reasonable solution.

**Comment by Louhike** [comment]
Yes, you're not the first one to give this feedback. The only CDI that I have is Xeno Crisis, so it was not a priority for me at first, but it is now.

**Comment by gingerbeardman** [comment]
Will try soon!

**Comment by Louhike** [comment]
I haven't released it yet, I'm testing it with another guy for a few days. I can send the binaries if you want to test it out/use it.
I'm also changed the UI, the tool now scan sub folders.
The last part I'm working on right now for this release is being able to use archives (7z, zip, rar, gz, bz, bz2, tar and lz).

**Comment by gingerbeardman** [comment]
No rush, I couldn't test right now anyway. I'll be patient.
