### ISSUE TITLE
Support for compressed files in Games directories

### ISSUE THREAD

**Issue by doragasu** [Louhike/Ugly-GDEmu-Games-Manager#55]
Currently for the scan algorithm to find and process games, they must be in extracted format. If they could be processed in compressed format, this could allow saving a lot of disk space in the host computer. In some extreme cases the saving can be about 1 GB per game. For example the Ikaruga TOSEC dump in ZIP format has a 58 MiB length, but when extracted it is 1.11 GiB long.

So could it be possible to add support for compressed game files? ZIP support could be enough, adding other formats like 7z and zstd would be also nice.

**Comment by Louhike** [comment]
That's a good idea! I need to check if it can be done quickly and I'll assign a milestone.

**Comment by doragasu** [comment]
Great! Thanks for taking this feature into consideration.

**Comment by Louhike** [comment]
There's an SDK for 7-zip which could be used: https://www.7-zip.org/sdk.html

**Comment by Louhike** [comment]
Done. Will be released in coming days with 0.7.0 version (currently in testing).

**Comment by Louhike** [comment]
Supported archives are zip, rar, 7zip, tar, bz, bz2, gz, lz. Only GDI are supported for now. The code for CDI is already done but it's taking too long so it is deactivated. I may add a configuration parameter or an option for it.

**Comment by doragasu** [comment]
Awesome, I'll test it ASAP, THANKS!

**Comment by Louhike** [comment]
It's not released yet, I'm currently testing (and fixing) it with someone else.

**Comment by doragasu** [comment]
Oh OK, then I'll test it when released.

Again, thanks!
