### ISSUE TITLE
Propeller Arena Won't Transfer?

### ISSUE THREAD

**Issue by Wakkowarner123** [Louhike/Ugly-GDEmu-Games-Manager#68]
"Cannot manage CDI with something else than two sessions." I checked with GD-ROM Explorer and verified that there were only 2 sessions, and tried several other dumps with the same result. Other CDI games work fine. Any ideas?
Thanks!

**Comment by Louhike** [comment]
Someone else told me they had this error in PM but I couldn't reproduce it. Could you provide me with the names of the games for which you had the error?

**Comment by Louhike** [comment]
Oh, there was one in the title, sorry. COuld you give the other ones though?

**Comment by Wakkowarner123** [comment]
It's just Propeller Arena, actually -- that's the only game that throws up this error. 
I've tried downloading it from different sources, and all of them have this problem with the software. I've read that there's never been a proper GDI dump of the game, so CDI format is the only way to play it.

**Comment by Wakkowarner123** [comment]
Just stumbled upon a gdemu compatible version someone made, I was able to transfer it, and it works great!
https://www.obscuregamers.com/threads/gdemu-audio-questions.2776/

**Comment by Louhike** [comment]
I found the reason of the error. It seems old CDI (before version 2147483654) stores the headset address differently.
