### ISSUE TITLE
0 games on PC found

### ISSUE THREAD

**Issue by icedkiller666** [Louhike/Ugly-GDEmu-Games-Manager#75]
**Describe the bug**
I'm trying to copy the CDI image of PSO and the software can't see it.

The CDI image is patched to work on private server and you can get it here: https://psopalace.sylverant.net/frameset.html

**To Reproduce**
1. extract the CDI to a folder ex: F:\IVES_PSOV2_US_R2
2. Make a scan of F:\IVES_PSOV2_US_R2
3. Result: 0 games found
4. But the CDI image is present. See screenshot

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5321533/119245858-6e73f800-bb4a-11eb-8b5e-8f1d13515717.png)

**Comment by Louhike** [comment]
Could you try to do the scan on the parent folder?
The application requires each game to be in its own folder or archive. So my guess is that it won't detect a game on a root folder like that.

**Comment by icedkiller666** [comment]
Correct, it does work like that, thanks!
